"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import type { SocialFeed, SocialFriends, SocialProfile } from "@/lib/social";
import { socialRequest, useSocialResource } from "@/lib/socialClient";
import { SocialShell, SocialStatus, formatPercent } from "@/components/social/SocialShared";
import { PickList } from "@/components/social/PickList";

export function FriendsView({ initialSearch = "" }: { initialSearch?: string }) {
  const friends = useSocialResource<SocialFriends>("view=friends");
  const feed = useSocialResource<SocialFeed>("view=feed");
  const [search, setSearch] = useState(initialSearch);
  const results = useSocialResource<SocialProfile[]>(search.length >= 2 ? `view=search&q=${encodeURIComponent(search)}` : null);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState("");
  async function friendship(username: string, operation: "request" | "accept" | "decline" | "remove") {
    setBusy(true); setNotice("");
    try { await socialRequest("", { action: "friend", username, operation }); setNotice(operation === "request" ? "Friend request sent." : operation === "accept" ? "You’re now friends." : operation === "decline" ? "Request declined." : "Friendship removed."); friends.reload(); feed.reload(); results.reload(); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Unable to update friendship."); }
    finally { setBusy(false); }
  }
  function person(profile: SocialProfile) {
    return <li key={profile.username} className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 py-4 last:border-0"><Link href={`/profile/${encodeURIComponent(profile.username)}`} className="flex items-center gap-3"><span aria-hidden="true" className="text-2xl">{profile.avatar}</span><span><span className="block text-sm font-bold">{profile.displayName}</span><span className="text-xs text-neutral-400">@{profile.username} · {profile.stats.wins}–{profile.stats.losses} · {formatPercent(profile.stats.winPercentage)}</span></span></Link><div className="flex flex-wrap gap-2">{profile.relationship === "none" ? <button disabled={busy} className="secondary-button" onClick={() => friendship(profile.username, "request")}>Add friend</button> : profile.relationship === "incoming" ? <><button disabled={busy} className="primary-button" onClick={() => friendship(profile.username, "accept")}>Accept</button><button disabled={busy} className="secondary-button" onClick={() => friendship(profile.username, "decline")}>Decline</button></> : profile.relationship === "outgoing" ? <><span className="self-center text-xs text-neutral-400">Request sent</span><button disabled={busy} className="secondary-button" onClick={() => friendship(profile.username, "remove")}>Cancel</button></> : profile.relationship === "friends" ? <button disabled={busy} className="secondary-button" onClick={() => friendship(profile.username, "remove")}>Remove</button> : null}</div></li>;
  }
  function find(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSearch(String(new FormData(event.currentTarget).get("username") ?? "").trim().toLowerCase()); }
  return <SocialShell title="Friends" eyebrow="Sports are better together" description="Share your pregame calls, tail a friend, and compare your records. A tailed pick is yours to keep, even if your friend changes their mind.">{!friends.data ? <SocialStatus error={friends.error} retry={friends.reload} /> : <><p role="status" className="mb-4 text-sm text-cyan-200">{notice}</p><div className="grid items-start gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="space-y-5"><section className="sport-panel p-6"><h2 className="text-xl font-black">Find your people</h2><form onSubmit={find} className="mt-4 flex gap-2"><label className="min-w-0 flex-1"><span className="sr-only">Search by username</span><input className="text-input" name="username" placeholder="Search username" minLength={2} maxLength={24} required defaultValue={initialSearch} /></label><button className="primary-button">Search</button></form>{search ? <div className="mt-4">{results.data ? results.data.length ? <ul>{results.data.map(person)}</ul> : <p className="text-sm text-neutral-400">No matching profiles.</p> : <SocialStatus error={results.error} retry={results.reload} />}</div> : null}</section>{friends.data.incoming.length ? <section className="sport-panel p-6"><h2 className="text-xl font-black">Friend requests</h2><ul>{friends.data.incoming.map(person)}</ul></section> : null}<section className="sport-panel p-6"><h2 className="text-xl font-black">Your friends · {friends.data.friends.length}</h2>{friends.data.friends.length ? <ul>{friends.data.friends.map(person)}</ul> : <p className="mt-3 text-sm leading-7 text-neutral-400">Search for a username and send your first friend request. Accepted friends can see and tail each other’s picks before game time.</p>}</section>{friends.data.outgoing.length ? <section className="sport-panel p-6"><h2 className="text-xl font-black">Requests sent</h2><ul>{friends.data.outgoing.map(person)}</ul></section> : null}</div><section><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-black">Friends picks & activity</h2><button className="secondary-button" onClick={feed.reload}>Refresh</button></div>{feed.data ? <PickList picks={feed.data.map((item) => item.pick)} allowTail reload={feed.reload} /> : <SocialStatus error={feed.error} retry={feed.reload} />}<p className="mt-4 text-xs leading-6 text-neutral-400">Activity follows submitted picks and their results. Community percentages on game cards use valid submitted picks; individual public history is hidden until lock.</p></section></div></>}</SocialShell>;
}
