"use client";

import Link from "next/link";
import { useState } from "react";
import type { SocialLeaderboard } from "@/lib/social";
import { useSocialResource } from "@/lib/socialClient";
import { SocialShell, SocialStatus, formatPercent } from "@/components/social/SocialShared";

export function LeaderboardView() {
  const [sport, setSport] = useState("overall");
  const [scope, setScope] = useState("community");
  const board = useSocialResource<SocialLeaderboard>(`view=leaderboard&sport=${sport}&scope=${scope}`);
  return <SocialShell title="Leaderboard" eyebrow="Earn your place" description="A meaningful sample comes first. Compare consistent pick records across the community or just your friends."><div className="mb-5 flex flex-wrap gap-4"><label className="text-sm">Sport<select value={sport} onChange={(event) => setSport(event.target.value)} className="ml-2 rounded-xl border border-white/15 bg-neutral-950 p-3"><option value="overall">Overall</option><option value="mlb">MLB</option><option value="nfl">NFL</option></select></label><label className="text-sm">Group<select value={scope} onChange={(event) => setScope(event.target.value)} className="ml-2 rounded-xl border border-white/15 bg-neutral-950 p-3"><option value="community">Community</option><option value="friends">Friends</option></select></label></div>{board.data ? <section className="sport-panel overflow-hidden"><p className="border-b border-white/10 p-5 text-xs leading-6 text-neutral-400">Minimum {board.data.minimumPicks} graded wins or losses in this category. Ranked by win percentage, then graded picks. Pushes, voids, and pending picks do not count toward eligibility.</p>{board.data.entries.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">{scope} {sport} leaderboard</caption><thead className="border-b border-white/10 text-xs uppercase text-neutral-400"><tr>{["Rank", "Player", "Record", "Win %", "Picks made"].map((label) => <th key={label} scope="col" className="whitespace-nowrap p-4">{label}</th>)}</tr></thead><tbody>{board.data.entries.map((entry) => <tr key={entry.username} className="border-b border-white/[.06] last:border-0"><td className="p-4 font-mono text-neutral-400">{entry.rank}</td><th scope="row" className="p-4"><Link href={`/profile/${encodeURIComponent(entry.username)}`} className="whitespace-nowrap text-cyan-200"><span aria-hidden="true">{entry.avatar}</span> @{entry.username}</Link></th><td className="whitespace-nowrap p-4 font-mono">{entry.wins}–{entry.losses}</td><td className="p-4 font-mono text-lime-200">{formatPercent(entry.winPercentage)}</td><td className="p-4 font-mono">{entry.picks}</td></tr>)}</tbody></table></div> : <div className="p-8"><h2 className="text-xl font-black">The season starts with your first pick.</h2><p className="mt-3 text-sm leading-7 text-neutral-400">No eligible records in this category yet. Keep making picks to reach the minimum sample.</p><Link className="primary-button mt-5" href="/">View games</Link></div>}</section> : <SocialStatus error={board.error} retry={board.reload} />}</SocialShell>;
}
