create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  access_tier text not null default 'free' check (access_tier in ('free', 'pro', 'friends_family')),
  pro_source text check (pro_source is null or pro_source in ('stripe', 'friends_family', 'admin')),
  pro_expires_at timestamptz,
  stripe_customer_id text unique,
  stripe_subscription_id text unique,
  subscription_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  code_hash text not null unique,
  label text not null default 'Friends & Family',
  redeemed_by uuid unique references public.profiles(id),
  redeemed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.favorite_teams (
  user_id uuid not null references public.profiles(id) on delete cascade,
  sport text not null check (sport in ('mlb', 'nfl')),
  team_id text not null,
  team_name text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, sport, team_id)
);

create table if not exists public.prediction_snapshots (
  id uuid primary key default gen_random_uuid(),
  sport text not null check (sport in ('mlb', 'nfl')),
  game_id text not null,
  scheduled_at timestamptz not null,
  away_team text not null,
  home_team text not null,
  pregame_predicted_winner text not null,
  pregame_home_win_probability double precision not null check (pregame_home_win_probability between 0 and 1),
  pregame_away_win_probability double precision not null check (pregame_away_win_probability between 0 and 1),
  model_version text not null,
  factors jsonb not null default '[]'::jsonb,
  locked_at timestamptz not null default now(),
  actual_winner text,
  away_score integer,
  home_score integer,
  final_at timestamptz,
  unique (sport, game_id)
);

create table if not exists public.saved_predictions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  prediction_id uuid not null references public.prediction_snapshots(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, prediction_id)
);

create table if not exists public.model_refresh_runs (
  id bigint generated by default as identity primary key,
  sport text not null check (sport in ('mlb', 'nfl')),
  ran_at timestamptz not null default now(),
  status text not null check (status in ('success', 'failed')),
  games_refreshed integer not null default 0,
  player_picks_refreshed integer not null default 0,
  error_message text
);

alter table public.profiles enable row level security;
alter table public.promo_codes enable row level security;
alter table public.favorite_teams enable row level security;
alter table public.prediction_snapshots enable row level security;
alter table public.saved_predictions enable row level security;
alter table public.model_refresh_runs enable row level security;

create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
create policy "favorite_teams_own" on public.favorite_teams for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "prediction_snapshots_public_read" on public.prediction_snapshots for select using (true);
create policy "saved_predictions_own" on public.saved_predictions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

revoke update on public.profiles from authenticated;
grant update (display_name) on public.profiles to authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.redeem_pro_code(p_code text)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  v_code public.promo_codes%rowtype;
  v_user uuid := auth.uid();
  v_hash text;
begin
  if v_user is null then
    return jsonb_build_object('ok', false, 'message', 'Sign in before redeeming a code.');
  end if;
  v_hash := encode(digest(upper(trim(p_code)), 'sha256'), 'hex');
  select * into v_code from public.promo_codes where code_hash = v_hash for update;
  if v_code.id is null then
    return jsonb_build_object('ok', false, 'message', 'That invite code is invalid.');
  end if;
  if v_code.redeemed_by is not null then
    return jsonb_build_object('ok', false, 'message', 'That invite code has already been used.');
  end if;

  update public.promo_codes
    set redeemed_by = v_user, redeemed_at = now()
    where id = v_code.id and redeemed_by is null;
  if not found then
    return jsonb_build_object('ok', false, 'message', 'That invite code has already been used.');
  end if;

  update public.profiles
    set access_tier = 'friends_family', pro_source = 'friends_family', pro_expires_at = null, updated_at = now()
    where id = v_user;
  return jsonb_build_object('ok', true, 'message', 'Permanent Friends & Family Pro is active.');
end;
$$;

revoke all on function public.redeem_pro_code(text) from public;
grant execute on function public.redeem_pro_code(text) to authenticated;

insert into public.promo_codes (code_hash, label) values
  ('4f346006d6c54fc8884c5c74936c1065607f16d324a14bc7663adb1b4d4b41d2', 'Initial Friends & Family 1'),
  ('9a9d195b7f16c0abd51eb877ffcb36c195cf9fa85b8b6c4f1a58b7ab41c6c92a', 'Initial Friends & Family 2'),
  ('76f2ae9dbceba4ea1d11f01574548c29b6d2ec0a09185443173b6e67a20a22a5', 'Initial Friends & Family 3'),
  ('736ef96766477814d63d583adcdb9304f90519bde24335f1e7247805ae6df166', 'Initial Friends & Family 4'),
  ('ce4fb362811ab7a1031f1735201fcf3793eb880cf8dadf40ff92b9281e0c4d5e', 'Initial Friends & Family 5')
on conflict (code_hash) do nothing;
